# Generated by Django 3.2.7 on 2021-09-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/testimonials'),
        ),
    ]
