# Generated by Django 3.2.7 on 2021-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('document', models.FileField(upload_to='docs/resources')),
            ],
        ),
        migrations.DeleteModel(
            name='NewsTeller',
        ),
    ]
