# Generated by Django 3.2.7 on 2021-09-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeActions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeactions',
            name='icon_class',
            field=models.CharField(default='not assigned', max_length=100),
        ),
    ]
