# Generated by Django 3.2.7 on 2021-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeActions', '0002_homeactions_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeactions',
            name='hex_color',
            field=models.CharField(default='#fc5a03', max_length=20),
        ),
    ]
