# Generated by Django 3.2.7 on 2021-09-25 05:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeActions', '0003_homeactions_hex_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeactions',
            name='name_slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
        ),
    ]
