# Generated by Django 3.2.7 on 2021-09-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeActions', '0005_alter_homeactions_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeactions',
            name='large_description',
            field=models.TextField(default='0', max_length=50000),
        ),
    ]
