# Generated by Django 3.2.7 on 2021-09-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeActions', '0006_homeactions_large_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeactions',
            name='large_description_doc',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='docs/'),
        ),
    ]
