# Generated by Django 3.2.7 on 2021-09-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeActions', '0007_homeactions_large_description_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeactions',
            name='large_description',
        ),
    ]
