# Generated by Django 3.2.7 on 2021-09-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeActions', '0008_remove_homeactions_large_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeactions',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='homeactions',
            name='large_description_doc',
        ),
        migrations.CreateModel(
            name='ActionBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletpoint', models.CharField(max_length=500)),
                ('Action', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HomeActions.homeactions')),
            ],
        ),
    ]
