# Generated by Django 3.2.7 on 2021-09-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeActions', '0009_auto_20210927_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('is_interested', models.BooleanField()),
                ('details', models.TextField(blank=True)),
                ('service_required', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HomeActions.homeactions')),
            ],
        ),
    ]
